version: '2.1'
services:
  build:
    build: .
    image: "sming/${PROJECT_NAME}"
    command: bash -c "make; chmod -R o+rw out/build; chmod -R o+rw out/firmware;"
    volumes:
      - .:/app

  clean:
    build: .
    image: "sming/${PROJECT_NAME}"
    command: make clean
    volumes:
      - .:/app

  upload:
    build: .
    image: "sming/${PROJECT_NAME}"
    command: make flash 
    volumes:
      - .:/app
    devices:
      - "${TTY_PATH:-/dev/ttyUSB0}:/dev/ttyUSB0"

  flashinit:
    build: .
    image: "sming/${PROJECT_NAME}"
    command: make flashinit
    volumes:
      - .:/app
    devices:
        - "${TTY_PATH:-/dev/ttyUSB0}:/dev/ttyUSB0"


